
start = acme-record / bundle / tstr
        

; All ACME records have the same structure
$admin-record /= [0xFFFF, acme-record]
acme-record = {
  id-chal,
  token-bundle,
  ? key-auth-digest ; present in Response Bundles
  ? alg-list ; present in Challenge Bundles
}
id-chal = (1 => bstr)
token-bundle = (2 => bstr)
key-auth-digest = (3 => [
    alg: alg-id,
    value: bstr
])
alg-list = (4 => [+ alg-id])
; From the IANA registry, only hash algorithms allowed
alg-id: tstr / int
